I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 60, in script
    e "test"
  File "game/script.rpy", line 10, in eline_speaking_callback
    renpy.show("M talking for 3s", at_list=(pos))
TypeError: 'ATLTransform' object is not iterable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 60, in script
    e "test"
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/character.py", line 1003, in do_display
    display_say(who,
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/character.py", line 501, in display_say
    c("begin", interact=interact, type=type, **cb_args)
  File "game/script.rpy", line 10, in eline_speaking_callback
    renpy.show("M talking for 3s", at_list=(pos))
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/exports.py", line 741, in show
    for i in at_list:
TypeError: 'ATLTransform' object is not iterable

macOS-14.2.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Cyber Soap 1.0
Mon Jan 22 15:48:30 2024
