I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 603, in script
    e_without_callback "test"
Exception: Sayer 'e_without_callback' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 603, in script
    e_without_callback "test"
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/pierregabrielbibalsobeaux/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'e_without_callback' is not defined.

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
Yofukashi 0.1 Development Build
Fri Aug  9 15:11:47 2024
